author: Sean Hammond
baseurl: /oatcake
description: The GitHub Pages theme that I use on seanh.cc
permalink: pretty
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-avatar
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
sass:
  style: compressed
title: Oatcake

github_ribbon: true

relative_links:
  enabled:     true
  collections: true
social:
  name: Sean Hammond
  links:
    - https://twitter.com/snhmnd
    - https://www.linkedin.com/in/sean-hammond-412b8425/
    - https://github.com/seanh
    - https://keybase.io/seanh
lang: en_GB
titles_from_headings:
  strip_title: true
  collections: true
