title: jekyll-theme-seanh
description: A plain and simple Jekyll / GitHub Pages theme
url: https://seanh.github.io/jekyll-theme-seanh/
author: Sean Hammond
baseurl: /jekyll-theme-seanh/
titles_from_headings:
  strip_title: true
  collections: true
permalink: /:categories/:year/:month/:day/:title
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-avatar
  - jekyll-feed
relative_links:
  enabled:     true
  collections: true
